# Generated by Django 3.0.6 on 2020-09-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, verbose_name='stud_fname')),
                ('lname', models.CharField(max_length=30, verbose_name='stud_lname')),
                ('email', models.EmailField(max_length=254, verbose_name='stud_email')),
                ('dob', models.CharField(max_length=30, verbose_name='stud_dob')),
                ('contact', models.BigIntegerField(verbose_name='stud_mob')),
                ('qual', models.CharField(max_length=30, verbose_name='stud_qual')),
                ('gender', models.CharField(max_length=30, verbose_name='stud_gen')),
                ('active', models.CharField(default='Y', max_length=30, verbose_name='active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
            ],
            options={
                'db_table': 'Stud_Info',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='cr_name')),
                ('code', models.CharField(max_length=30, verbose_name='cr_code')),
                ('fees', models.FloatField(verbose_name='cr_fee')),
                ('duration', models.CharField(max_length=30, verbose_name='cr_duration')),
                ('active', models.CharField(default='Y', max_length=30, verbose_name='active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('studrefs', models.ManyToManyField(related_name='courserefs', to='studreg.Student')),
            ],
            options={
                'db_table': 'Courses_Info',
            },
        ),
    ]
